// <auto-generated />
using DotAgroAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotAgroAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230311165340_Premiere Migration")]
    partial class PremiereMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DotAgroAPI.Data.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mail");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("Headquarter_PK");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("DotAgroAPI.Data.Models.Headquarter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("city");

                    b.HasKey("Id")
                        .HasName("Headquarter_PK");

                    b.ToTable("Headquarter", (string)null);
                });

            modelBuilder.Entity("DotAgroAPI.Data.Models.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("firstname");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<int>("IdHeadquarter")
                        .HasColumnType("int")
                        .HasColumnName("id_headquarter");

                    b.Property<int>("IdService")
                        .HasColumnType("int")
                        .HasColumnName("id_service");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("lastname");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mail");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("Salary_PK");

                    b.HasIndex("IdHeadquarter");

                    b.HasIndex("IdService");

                    b.ToTable("Salary", (string)null);
                });

            modelBuilder.Entity("DotAgroAPI.Data.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("Service_PK");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("DotAgroAPI.Data.Models.Salary", b =>
                {
                    b.HasOne("DotAgroAPI.Data.Models.Headquarter", "IdHeadquarterNavigation")
                        .WithMany("Salaries")
                        .HasForeignKey("IdHeadquarter")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("Salary_HeadquarterFK");

                    b.HasOne("DotAgroAPI.Data.Models.Service", "IdServiceNavigation")
                        .WithMany("Salaries")
                        .HasForeignKey("IdService")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("Salary_ServiceFK");

                    b.Navigation("IdHeadquarterNavigation");

                    b.Navigation("IdServiceNavigation");
                });

            modelBuilder.Entity("DotAgroAPI.Data.Models.Headquarter", b =>
                {
                    b.Navigation("Salaries");
                });

            modelBuilder.Entity("DotAgroAPI.Data.Models.Service", b =>
                {
                    b.Navigation("Salaries");
                });
#pragma warning restore 612, 618
        }
    }
}
